CREATE TABLE IF NOT EXISTS raw_user (
    user_id VARCHAR(500),
    name VARCHAR(500),
    review_count VARCHAR(500),
    yelping_since VARCHAR(500),
    useful VARCHAR(500),
    funny VARCHAR(500),
    cool VARCHAR(500),
    elite TEXT,
    friends TEXT,
    fans VARCHAR(500),
    average_stars VARCHAR(500),
    compliment_hot VARCHAR(500),
    compliment_more VARCHAR(500),
    compliment_profile VARCHAR(500),
    compliment_cute VARCHAR(500),
    compliment_list VARCHAR(500),
    comliment_note VARCHAR(500),
    compliment_plain VARCHAR(500),
    compliment_cool VARCHAR(500),
    compliment_funny VARCHAR(500),
    compliment_writer VARCHAR(500),
    compliment_photos VARCHAR(500)
);