CREATE TABLE IF NOT EXISTS std_user (
  user_id VARCHAR(22) PRIMARY KEY, 
  name VARCHAR(255) NOT NULL, 
  review_count INT NOT NULL, 
  yelping_since TIMESTAMP NOT NULL, 
  friends TEXT[] NOT NULL,
  friends_count INT NOT NULL,  
  useful INT NOT NULL, 
  funny INT NOT NULL, 
  cool INT NOT NULL, 
  fans INT NOT NULL, 
  elite TEXT[] NOT NULL,
  elite_count INT NOT NULL,
  average_stars FLOAT NOT null,
  compliment_hot INT NOT null,
  compliment_more INT NOT null,
  compliment_profile INT NOT NULL,
  compliment_cute INT NOT NULL,
  compliment_list INT NOT NULL,
  comliment_note INT NOT NULL,
  compliment_plain INT NOT NULL,
  compliment_cool INT NOT NULL,
  compliment_funny INT NOT NULL,
  compliment_writer INT NOT NULL,
  compliment_photos INT NOT NULL
);