create table if not exists std_business ( 
  business_id VARCHAR(22) PRIMARY KEY, 
  name VARCHAR(255) NOT NULL, 
  address VARCHAR(255) NOT NULL, 
  city VARCHAR(255) NOT NULL, 
  state VARCHAR(55) NOT NULL, 
  postal_code VARCHAR(255) NOT NULL,
  latitude FLOAT NOT NULL, 
  longitude FLOAT NOT NULL, 
  stars FLOAT NOT NULL, 
  review_count INT NOT NULL, 
  is_open boolean NOT NULL,  
  categories TEXT[],
  hours_sun_from TIME,
  hours_sun_to TIME,
  hours_mon_from TIME,
  hours_mon_to TIME,
  hours_tues_from TIME,
  hours_tues_to TIME,
  hours_wed_from TIME,
  hours_wed_to TIME,
  hours_thurs_from TIME,
  hours_thurs_to TIME,
  hours_fri_from TIME,
  hours_fri_to TIME,
  hours_sat_from TIME,
  hours_sat_to TIME,
  accepts_insurance BOOLEAN NOT NULL,
  accepts_credit_card BOOLEAN NOT NULL,
  ages_allowed VARCHAR(55),
  by_appointment_only BOOLEAN NOT null,
  bike_parking BOOLEAN NOT NULL,
  dogs_allowed BOOLEAN NOT NULL,
  good_for_dancing BOOLEAN NOT NULL,
  good_for_kids BOOLEAN NOT NULL,
  happy_hour BOOLEAN NOT null,
  noise_level VARCHAR(55) NOT null,
  open_24_hours BOOLEAN NOT null,
  outdoor_seating BOOLEAN NOT null,
  restaurants_attire VARCHAR(255) NOT null,
  restaurants_reservation BOOLEAN NOT null,
  restaurants_good_for_groups BOOLEAN NOT null,
  restaurants_delivery BOOLEAN NOT null,
  restaurants_table_service BOOLEAN NOT null,
  smoking VARCHAR(55) NOT null,
  wheel_chair_accessible BOOLEAN NOT null,
  wifi varchar(55) NOT null
  );